language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - g++
    - libpng-dev
    - libsdl2-dev
    - imagemagick

sudo: false

env:
  matrix:
    - BUILDTYPE=CMAKE
    - BUILDTYPE=GNUMAKE
    - BUILDTYPE=ASAN
    - BUILDTYPE=SHARED

script:
  - if [[ "$BUILDTYPE" == "GNUMAKE" ]]; then make ; make test ;  fi
  - if [[ "$BUILDTYPE" == "ASAN" ]]; then cmake -DUSE_ASAN=ON . ; make ; fi
  - if [[ "$BUILDTYPE" == "CMAKE" ]]; then cmake . ; make ; fi
  - if [[ "$BUILDTYPE" == "SHARED" ]] ; then cmake -DSHARED=ON .;  make ; fi 
